# Generated by Django 4.2.28 on 2026-02-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('check_interval', models.PositiveIntegerField(default=5, help_text='Frequency of checks in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('is_success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitor.website')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
