# Generated by Django 4.2.28 on 2026-02-21 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_website_authorized_users_alter_website_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorlog',
            name='payload_size',
            field=models.IntegerField(blank=True, help_text='Payload size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ttfb',
            field=models.FloatField(blank=True, help_text='Time to first byte in seconds', null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='alert_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Consecutive failures before critical alert'),
        ),
        migrations.AddField(
            model_name='website',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='consecutive_successes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='failure_poll_interval',
            field=models.PositiveIntegerField(default=5, help_text='Poll frequency in seconds when down'),
        ),
        migrations.AddField(
            model_name='website',
            name='recovery_threshold',
            field=models.PositiveIntegerField(default=2, help_text='Consecutive successes before marking UP'),
        ),
        migrations.AlterField(
            model_name='website',
            name='check_interval',
            field=models.PositiveIntegerField(default=5, help_text='Standard frequency in minutes'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('mttr_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitor.website')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
