# Generated by Django 4.2.28 on 2026-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorlog_payload_size_monitorlog_ttfb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_postgres_url', models.CharField(blank=True, max_length=500, null=True)),
                ('custom_redis_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
