# Generated by Django 4.2.28 on 2026-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='cpu_alert_threshold',
            field=models.IntegerField(default=85, help_text='CPU percentage'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='disk_alert_threshold',
            field=models.IntegerField(default=85, help_text='Disk percentage'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='memory_alert_threshold',
            field=models.IntegerField(default=85, help_text='RAM percentage'),
        ),
    ]
