# Generated by Django 4.2.28 on 2026-02-21 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_systemconfig_alert_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('disk', models.FloatField()),
                ('load_1', models.FloatField(default=0)),
                ('load_5', models.FloatField(default=0)),
                ('load_15', models.FloatField(default=0)),
                ('net_sent', models.BigIntegerField(default=0)),
                ('net_recv', models.BigIntegerField(default=0)),
                ('response_time', models.FloatField(blank=True, help_text='In seconds, if triggered by latency spike', null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='monitor.incident')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='monitor.website')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
